FROM node:lts-alpine
ENV NODE_ENV=production
ENV HOSTNAME "0.0.0.0"
WORKDIR /usr/src/app
COPY ["package.json", "package-lock.json*", "npm-shrinkwrap.json*", "./"]
RUN npm install --production --silent && mv node_modules ../
COPY prisma ./prisma
RUN npx prisma generate
RUN npx prisma db push
COPY . .
EXPOSE 9000
RUN chown -R node /usr/src/app
USER node
CMD ["npm", "start"]